import { test, expect, type Page } from '@playwright/test';

async function visit(page: Page, path: string) {
  await page.goto(path, { waitUntil: 'domcontentloaded' });
}

async function enterDemo(page: Page) {
  await visit(page, '/admin/login');
  await page.getByRole('button', { name: 'Open demo workspace' }).click();
  await expect(page.getByRole('heading', { name: 'Dashboard overview' })).toBeVisible();
}

test('administrator routes require an explicit demo session and logout removes access', async ({ page }) => {
  await visit(page, '/admin/services');
  await expect(page).toHaveURL(/\/admin\/login$/);
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Email address' })).toHaveValue('');
  await expect(page.getByLabel('Password')).toHaveValue('');
  await page.getByRole('button', { name: 'Open demo workspace' }).click();
  await expect(page.getByRole('heading', { name: 'Dashboard overview' })).toBeVisible();
  await page.reload({ waitUntil: 'domcontentloaded' });
  await expect(page.getByRole('heading', { name: 'Dashboard overview' })).toBeVisible();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page).toHaveURL(/\/admin\/login$/);
  await visit(page, '/admin/contact-messages');
  await expect(page).toHaveURL(/\/admin\/login$/);
});

test('bilingual content can be created, edited, published, hidden, searched and deleted', async ({ page }) => {
  await enterDemo(page);
  await visit(page, '/admin/features');
  await page.getByRole('button', { name: 'Add new', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Title · English').fill('Workshop transparency test');
  await dialog.getByLabel('Title · Arabic').fill('شفافية ورشة الاختبار');
  await dialog.getByLabel('Short description · English').fill('A clear, written service estimate before work begins.');
  await dialog.getByLabel('Short description · Arabic').fill('تقدير مكتوب وواضح للخدمة قبل بدء العمل.');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await page.getByRole('textbox', { name: 'Search records' }).fill('Workshop transparency test');
  let row = page.getByRole('row').filter({ hasText: 'Workshop transparency test' });
  await expect(row).toContainText('Draft');
  await visit(page, '/features');
  await expect(page.getByRole('heading', { name: 'Workshop transparency test', exact: true })).toHaveCount(0);
  await visit(page, '/admin/features');
  await page.getByRole('textbox', { name: 'Search records' }).fill('Workshop transparency test');
  row = page.getByRole('row').filter({ hasText: 'Workshop transparency test' });
  await row.getByRole('button', { name: 'Edit record', exact: true }).click();
  await dialog.getByLabel('Title · English').fill('Workshop transparency published');
  await dialog.getByRole('tab', { name: 'Publishing', exact: true }).click();
  await dialog.getByLabel('Publication status').selectOption('published');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await visit(page, '/features');
  await expect(page.getByRole('heading', { name: 'Workshop transparency published', exact: true })).toBeVisible();
  await visit(page, '/admin/features');
  await page.getByRole('textbox', { name: 'Search records' }).fill('Workshop transparency published');
  row = page.getByRole('row').filter({ hasText: 'Workshop transparency published' });
  await row.getByRole('button', { name: 'Publish / unpublish', exact: true }).click();
  await expect(row).toContainText('Draft');
  await visit(page, '/features');
  await expect(page.getByRole('heading', { name: 'Workshop transparency published', exact: true })).toHaveCount(0);
  await visit(page, '/admin/features');
  await page.getByRole('textbox', { name: 'Search records' }).fill('Workshop transparency published');
  row = page.getByRole('row').filter({ hasText: 'Workshop transparency published' });
  await row.getByRole('button', { name: 'Delete record', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Delete this record?' })).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(dialog).toHaveCount(0);
  await expect(row).toBeVisible();
  await expect(row.getByRole('button', { name: 'Delete record', exact: true })).toBeFocused();
  await row.getByRole('button', { name: 'Delete record', exact: true }).click();
  await dialog.getByRole('button', { name: 'Delete record', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'No matching results' })).toBeVisible();
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.getByRole('textbox', { name: 'Search records' }).fill('Workshop transparency published');
  await expect(page.getByRole('heading', { name: 'No matching results' })).toBeVisible();
});

test('footer settings, homepage copy and statistics reach the public website', async ({ page }) => {
  await enterDemo(page);
  await visit(page, '/admin/settings/footer');
  await page.getByLabel('Footer description · English').fill('Personal automotive expertise, verified by this CMS test.');
  await page.getByRole('button', { name: 'Save settings' }).click();
  await expect(page.getByRole('status')).toContainText('Your website settings have been saved.');
  await visit(page, '/admin/settings/website');
  await page.getByLabel('Statistic 1 · Value', { exact: true }).fill('17+');
  await page.getByLabel('Statistic 1 · English label').fill('Years of dedicated automotive care');
  await page.getByRole('button', { name: 'Save settings' }).click();
  await expect(page.getByRole('status')).toContainText('Your website settings have been saved.');
  await visit(page, '/admin/pages');
  await page.getByRole('textbox', { name: 'Search records' }).fill('home');
  const homeRow = page.getByRole('row').filter({ has: page.locator('small', { hasText: /^home$/ }) });
  await homeRow.getByRole('button', { name: 'Edit record', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('tab', { name: 'Details', exact: true }).click();
  await dialog.getByLabel('Introduction title · English').fill('Your automotive story starts with care.');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await visit(page, '/');
  await expect(page.locator('footer')).toContainText('Personal automotive expertise, verified by this CMS test.');
  await expect(page.getByRole('heading', { name: 'Your automotive story starts with care.', exact: true })).toBeVisible();
  await expect(page.locator('.stats-strip')).toContainText('17+');
  await expect(page.locator('.stats-strip')).toContainText('Years of dedicated automotive care');
});

test('media uploads render previews and retain bilingual alt text after editing', async ({ page }) => {
  await enterDemo(page);
  await visit(page, '/admin/media');
  await page.getByRole('button', { name: 'Upload media', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.locator('input[type=file]').setInputFiles({ name: 'workshop-check.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aHuoAAAAASUVORK5CYII=', 'base64') });
  await dialog.getByLabel('Image title · English').fill('Workshop media test');
  await dialog.getByLabel('Image title · Arabic').fill('صورة اختبار الورشة');
  await dialog.getByLabel('Alt text · English').fill('A workshop image used for verification');
  await dialog.getByLabel('Alt text · Arabic').fill('صورة ورشة للتحقق');
  await dialog.getByRole('button', { name: 'Upload image', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await page.getByRole('textbox', { name: 'Search records' }).fill('Workshop media test');
  const card = page.locator('.admin-media-card').filter({ hasText: 'Workshop media test' });
  const preview = card.locator('img');
  await expect(preview).toHaveAttribute('src', /^data:image\/png;base64,/);
  await expect.poll(() => preview.evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBeTruthy();
  await card.getByRole('button', { name: 'Edit image', exact: true }).click();
  await dialog.getByRole('tab', { name: 'Media', exact: true }).click();
  await dialog.getByLabel('Image alt text · English').fill('Updated workshop image description');
  await dialog.getByLabel('Image alt text · Arabic').fill('وصف محدث لصورة الورشة');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await expect(preview).toHaveAttribute('alt', 'Updated workshop image description');
  await page.reload({ waitUntil: 'domcontentloaded' });
  await page.getByRole('textbox', { name: 'Search records' }).fill('Workshop media test');
  await card.getByRole('button', { name: 'Edit image', exact: true }).click();
  await dialog.getByRole('tab', { name: 'Media', exact: true }).click();
  await expect(dialog.getByLabel('Image alt text · Arabic')).toHaveValue('وصف محدث لصورة الورشة');
  await page.keyboard.press('Escape');
  await card.getByRole('button', { name: 'Delete image', exact: true }).click();
  await dialog.getByRole('button', { name: 'Delete record', exact: true }).click();
  await expect(card).toHaveCount(0);
});

test('public messages and subscriptions can be managed privately by the administrator', async ({ page }) => {
  await visit(page, '/contact');
  await page.getByLabel('Full name').fill('Apex QA Customer');
  await page.locator('#contact-email').fill('qa.customer@example.test');
  await page.locator('#contact-subject').selectOption('general');
  await page.getByLabel('Your message', { exact: false }).fill('Please help me arrange a maintenance appointment next week.');
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('MESSAGE RECEIVED');
  await visit(page, '/newsletter');
  const form = page.locator('.newsletter-form').first();
  await form.getByRole('textbox', { name: 'Your email address' }).fill('qa.subscriber@example.test');
  await form.getByRole('button', { name: 'Subscribe', exact: true }).click();
  await expect(form).toContainText('You’re on the list. Welcome to Apex.');
  await enterDemo(page);
  await visit(page, '/admin/contact-messages');
  await page.getByRole('textbox', { name: 'Search records' }).fill('Apex QA Customer');
  const row = page.getByRole('row').filter({ hasText: 'Apex QA Customer' });
  await expect(row).toContainText('Unread');
  await row.getByRole('button', { name: 'Read message', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog).toContainText('Please help me arrange a maintenance appointment next week.');
  await dialog.getByRole('button', { name: 'Mark read', exact: true }).click();
  await expect(dialog.getByRole('button', { name: 'Mark unread', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.getByLabel('Filter by status').selectOption('unread');
  await expect(page.getByRole('heading', { name: 'No matching results' })).toBeVisible();
  await page.getByLabel('Filter by status').selectOption('read');
  await expect(row).toBeVisible();
  await visit(page, '/admin/newsletter-subscribers');
  await page.getByRole('textbox', { name: 'Search records' }).fill('qa.subscriber@example.test');
  const subscriber = page.getByRole('row').filter({ hasText: 'qa.subscriber@example.test' });
  await subscriber.getByRole('button', { name: 'Edit record', exact: true }).click();
  await dialog.getByLabel('Subscription status').selectOption('inactive');
  await dialog.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  await expect(subscriber).toContainText('Inactive');
  await page.getByLabel('Filter by status').selectOption('active');
  await expect(page.getByRole('heading', { name: 'No matching results' })).toBeVisible();
  await page.getByLabel('Filter by status').selectOption('inactive');
  await subscriber.getByRole('button', { name: 'Delete record', exact: true }).click();
  await dialog.getByRole('button', { name: 'Delete record', exact: true }).click();
  await expect(subscriber).toHaveCount(0);
});

test('hero buttons, footer navigation and testimonial edits persist into public content', async ({ page }) => {
  await enterDemo(page);
  await visit(page, '/admin/hero-slides');
  await page.getByRole('textbox', { name: 'Search records' }).fill('driven-by-excellence');
  await page.getByRole('row').filter({ hasText: 'driven-by-excellence' }).getByRole('button', { name: 'Edit record', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('tab', { name: 'Details', exact: true }).click();
  await dialog.getByLabel('Primary button · English').fill('Plan your next service');
  await dialog.getByLabel('Primary button · Arabic').fill('خطط لخدمتك القادمة');
  await dialog.getByLabel('Primary button link').fill('/contact?service=maintenance-service');
  await dialog.getByLabel('Secondary button · English').fill('Explore our collections');
  await dialog.getByLabel('Secondary button · Arabic').fill('اكتشف مجموعاتنا');
  await dialog.getByLabel('Secondary button link').fill('/gallery');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await visit(page, '/admin/navigation-items');
  await page.getByRole('button', { name: 'Add new', exact: true }).click();
  await dialog.getByLabel('Title · English').fill('Ownership guide');
  await dialog.getByLabel('Title · Arabic').fill('دليل الملكية');
  await dialog.getByRole('tab', { name: 'Details', exact: true }).click();
  await dialog.getByLabel('Destination URL').fill('/faq');
  await dialog.getByLabel('Menu location').selectOption('footer');
  await dialog.getByRole('tab', { name: 'Publishing', exact: true }).click();
  await dialog.getByLabel('Publication status').selectOption('published');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await visit(page, '/admin/testimonials');
  await page.getByRole('row').filter({ hasText: 'Omar H.' }).getByRole('button', { name: 'Edit record', exact: true }).click();
  await dialog.getByLabel('Customer quote · English').fill('The workshop explained every detail and made the next step effortless.');
  await dialog.getByLabel('Customer quote · Arabic').fill('شرح فريق الورشة كل التفاصيل وجعل الخطوة التالية سهلة.');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await visit(page, '/');
  await expect(page.locator('.hero-buttons').getByRole('link', { name: 'Plan your next service' })).toHaveAttribute('href', '/contact?service=maintenance-service');
  await expect(page.locator('.hero-buttons').getByRole('link', { name: 'Explore our collections' })).toHaveAttribute('href', '/gallery');
  await expect(page.locator('footer').getByRole('link', { name: 'Ownership guide', exact: true })).toHaveAttribute('href', '/faq');
  await expect(page.locator('header').getByRole('link', { name: 'Ownership guide', exact: true })).toHaveCount(0);
  await expect(page.locator('.testimonials-section')).toContainText('The workshop explained every detail and made the next step effortless.');
});

test('service benefits and process, bilingual blog metadata and FAQ answers remain editable', async ({ page }) => {
  await enterDemo(page);
  await visit(page, '/admin/services');
  await page.getByRole('row').filter({ hasText: 'vehicle-sales' }).getByRole('button', { name: 'Edit record', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Full content · English').fill('Our specialist will help you compare carefully selected vehicles and find the right next step.');
  await dialog.getByRole('tab', { name: 'Details', exact: true }).click();
  await dialog.getByLabel('Benefits · English (one per line)').fill('A personal consultation with your advisor\nA documented vehicle history review');
  await dialog.getByLabel('Service process · English (one step per line)').fill('Discuss your driving priorities\nArrange your vehicle viewing');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await visit(page, '/services/vehicle-sales');
  await expect(page.getByText('A documented vehicle history review', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Discuss your driving priorities', exact: true })).toBeVisible();
  await visit(page, '/admin/blog-posts');
  await page.getByRole('row').filter({ hasText: 'the-art-of-preventive-maintenance' }).getByRole('button', { name: 'Edit record', exact: true }).click();
  await dialog.getByRole('tab', { name: 'Details', exact: true }).click();
  await dialog.getByLabel('Author · English').fill('Apex Workshop Editor');
  await dialog.getByLabel('Author · Arabic').fill('محرر ورشة أبيكس');
  await dialog.getByLabel('Tags · English (one per line)').fill('Workshop expertise\nOwner confidence');
  await dialog.getByLabel('Tags · Arabic (one per line)').fill('خبرة الورشة\nثقة المالك');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await visit(page, '/blog/the-art-of-preventive-maintenance');
  await expect(page.getByText('Apex Workshop Editor', { exact: true })).toBeVisible();
  await expect(page.getByText('Owner confidence', { exact: true })).toBeVisible();
  await visit(page, '/admin/faqs');
  await page.getByRole('row').filter({ hasText: 'arrange-viewing' }).getByRole('button', { name: 'Edit record', exact: true }).click();
  await dialog.getByLabel('Answer · English').fill('Contact your Apex advisor to arrange a personal viewing and discuss a suitable test drive.');
  await dialog.getByRole('tab', { name: 'Details', exact: true }).click();
  await dialog.getByLabel('Category · English').fill('Vehicle ownership');
  await dialog.getByLabel('Category · Arabic').fill('ملكية السيارات');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await visit(page, '/faq');
  await page.getByRole('button', { name: 'Can I arrange a vehicle viewing and test drive?', exact: true }).click();
  await expect(page.getByText('Contact your Apex advisor to arrange a personal viewing and discuss a suitable test drive.', { exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Vehicle ownership', exact: true })).toBeVisible();
});
