import { test, expect } from '@playwright/test';
import seed from '../src/data/seed.json' with { type: 'json' };

test('global SEO defaults and testimonial ratings survive reload and reach the homepage', async ({ page }) => {
  await page.goto('/admin/login');
  await page.getByRole('button', { name: 'Open demo workspace' }).click();
  await page.goto('/admin/pages');
  await page.getByRole('textbox', { name: 'Search records' }).fill('home');
  await page.getByRole('row').filter({ has: page.locator('small', { hasText: /^home$/ }) }).getByRole('button', { name: 'Edit record', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('tab', { name: 'SEO', exact: true }).click();
  await dialog.getByLabel('SEO title · English').fill('');
  await dialog.getByLabel('Meta description · English').fill('');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await page.goto('/admin/settings/seo');
  await page.getByLabel('Default SEO title · English').fill('The global Apex title');
  await page.getByLabel('Default meta description · English').fill('The global automotive description managed in site settings.');
  await page.getByRole('button', { name: 'Save settings' }).click();
  await expect(page.getByRole('status')).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Default SEO title · English')).toHaveValue('The global Apex title');
  await page.goto('/');
  await expect(page).toHaveTitle('The global Apex title | Apex Motors');
  await expect(page.locator('meta[name="description"]')).toHaveAttribute('content', 'The global automotive description managed in site settings.');
  await page.goto('/admin/testimonials');
  await page.getByRole('textbox', { name: 'Search records' }).fill(seed.testimonials[0].title_en);
  await page.getByRole('row').filter({ hasText: seed.testimonials[0].title_en }).getByRole('button', { name: 'Edit record', exact: true }).click();
  await dialog.getByRole('tab', { name: 'Details', exact: true }).click();
  await dialog.getByLabel('Rating (1–5)').fill('3');
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await page.goto('/');
  await page.reload();
  const stars = page.locator('.testimonial-card').filter({ hasText: seed.testimonials[0].title_en }).locator('.stars');
  await expect(stars).toHaveAttribute('aria-label', '3 out of 5 stars');
  await expect(stars.locator('svg[fill="currentColor"]')).toHaveCount(3);
});

test('active and inactive publishing state persists and controls a service detail route', async ({ page }) => {
  await page.goto('/admin/login');
  await page.getByRole('button', { name: 'Open demo workspace' }).click();
  await page.goto('/admin/services');
  const row = page.getByRole('row').filter({ hasText: seed.services[0].title_en });
  await row.getByRole('button', { name: 'Edit record', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByRole('tab', { name: 'Publishing', exact: true }).click();
  await dialog.getByRole('checkbox', { name: /Active on the website/ }).uncheck();
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await page.goto(`/services/${seed.services[0].slug}`);
  await expect(page.getByRole('heading', { name: 'Let’s get you back on track.' })).toBeVisible();
  await page.goto('/admin/services');
  await row.getByRole('button', { name: 'Edit record', exact: true }).click();
  await dialog.getByRole('tab', { name: 'Publishing', exact: true }).click();
  await expect(dialog.getByRole('checkbox', { name: /Active on the website/ })).not.toBeChecked();
  await dialog.getByRole('checkbox', { name: /Active on the website/ }).check();
  await dialog.getByRole('button', { name: 'Save changes' }).click();
  await expect(dialog).toHaveCount(0);
  await page.goto(`/services/${seed.services[0].slug}`);
  await expect(page.locator('main h1')).toHaveText(seed.services[0].title_en);
});
